const foodFacts = ["Geomelophagia is someone who has the urge to eat raw potatoes.",
"9th August is officially National Rice Pudding Day.",
"Rice can be used in beer, dog food, baby food, breakfast cereals, snacks, frozen foods and sauces!",
"October is National Pasta Month.",
"Canadian neurosurgeon Dr. Wilder Penfield, while operating on epilepsy patients, discovered the Toast Centre of the human brain, which is wholly dedicated to detecting when toast is burning!",
"16 billion jelly beans are made for Easter. Stacked end to end, the jelly beans would circle the globe nearly 3 times!",
"Before 1991 Twix Bars were internationally known as Raider.",
"The Arabs invented caramel.",
"Before Walkers owned Wotsits, they sold a rival known as Cheetos on the UK market.",
"Pringles</a> were first sold in America in 1968 but were not popular until the mid-1970s.",
"Saddam Hussein liked Bounty Bars!",
"Frank Mars invented the Snickers chocolate bar. He named it Snickers after his favorite horse.",
"The Ms in M & Ms stand for Mars & Murrie, the co-creators of the candy.",
"Twinkies originally had banana flavored filling, but switched to vanilla when World War 2 bought the banana trade to a halt.",
"Cadburys Cream Eggs first went on sale in 1971.",
"In 2006, Sharis Berries pioneered the concept of delivering chocolate dipped fruits nationwide in freeze packs.",
"The Kit Kat was originally made by Rowntree Limited, until 1988 when they were bought out by Nestle.",
"Juicy Fruit and Wrigleys Spearmint gums are more than 100 years old!",
"Hundreds and Thousands (Sprinkles, Nonpareils, Jimmies) are small round balls of brightly colored sugar used as decorations on cakes, cookies, trifles and other desserts. Their use dates back at least to the early 19th century.",
"Gummy Bears are only 79 millimeters in length.",
"Chocolate can kill dogs; it directly affects their heart and nervous system.",
"Deep fried chocolate bars contain about 850 calories per bar.",
"The worlds oldest chocolates are 106 years old. A tin of chocolates from the coronation of King Edward VII from 1902.",
"Yorkie Chocolate Bars are not for girls!",
"Sugar is the only taste that humans are born craving.",
"The Swiss eat the most chocolate, followed by the English.",
"The Bourbon biscuit was introduced in 1910 originally under the name Creola.",
"In 15th century France, chocolate could only be eaten by members of the royal court.",
"Gorgonzola cheese dates back to the year 879!",
"Many mass-produced ice creams have seaweed in them.",
"Cheese products contain less than 51% cheese.",
"Some yoghurt contain beef or pork gelatin.",
"The weight of a Babybel is 21 grams.",
"An average American will eat the equivalent of 28 pigs in their lifetime.",
"National Pigs-in-a-Blanket Day is celebrated on 24th April every year.",
"The first soup was made from hippopotamus and dates back to 6000 B.C.",
"Baked beans are low in fat and have a lot of fiber and protein.",
"Worcestershire sauce is made from dissolved fish.",
"Pescetarians are vegetarians who eat fish.",
"The largest item on any menu in the world is the roast camel.",
"Egg yolks are one of the few foods that naturally contain Vitamin D.",
"The average hot dog is consumed in 6 bites.",
"Until well into the sixteenth century, bacon was a Middle English term used to refer to all pork in general.",
"In America, anchovies always rank last on the list of favorite toppings.",
"The average amount of meat eaten per person, per year is 78.5kg.",
"French fries came from Belgium, but are most popular in the US.",
"An average person will consume 12 pubic hairs in their fast food every year!",
"KFC (Kentucky Fried Chicken) was founded by Colonel Harland Sanders in 1952.",
"We eat 300 million portions of fish and chips in Britain each year.",
"Chicken McNuggets contain beef additives.",
"Apples, pears, cherries and strawberries are all members of the rose family.",
"The word vegetable has no scientific definition, so its still acceptable to call a tomato a vegetable.",
"In the Philippines, it is considered good luck if a coconut is cleanly split open without jagged edges.",
"When cranberries are ripe, they bounce like a rubber ball.",
"The highest number of grapes eaten in 3 minutes is 133. This record was set in 2001 by Mat Hand, from the UK.",
"There are more than 10,000 varieties of tomatoes.",
"In 2001, there were more than 300 banana-related accidents in Britain, most involving people slipping on skins.",
"If you want to speed up the ripening of a pineapple, so that you can eat it faster, then you can do it by standing it upside down (on the leafy end).",
"Carrots have zero fat content.",
"Peanuts can be used to make dynamite.",
"A watermelon is over 92% water by weight.",
"Alliumphobia is the fear of garlic.",
"A row of corn always has an even number.",
"The pumpkin originated in Mexico about 9,000 years ago.",
"Square watermelons sell for about $85.",
"Turnips are high in fiber, Vitamin C, Calcium and Potassium.",
"Eating a lot of beetroot turns your pee into a pink color.",
"Biting a wooden spoon whilst chopping an onion will stop your eyes from watering.",
"Each pineapple plant only produces just one pineapple per year.",
"Lettuce is a member of the sunflower family.",
"Blueberries are a good source of Vitamin C and fiber.",
"Pumpkin flowers are edible.",
"Peaches are the third most popular fruit grown in America.",
"We are eating 900% more broccoli than we did 20 years ago.",
"A survey showed 29% of adults say they have been splashed or scalded by hot drinks while dunking biscuits.",
"Ortharexia Nervosa is an eating disorder where the sufferer is obsessed with eating healthy food.",
"Ketchup was sold in the 1830s as medicine.",
"Dry swallowing one teaspoon of sugar can commonly cure hic-ups.",
"In Kentucky, it is illegal to carry an ice cream cone in your back pocket.",
"The fear of cooking is known as Mageirocophobia and is a recognized phobia.",
"The tea bag was introduced in 1908 by Thomas Sullivan of New York.",
"The tall chefs hat is called a toque.",
"Arachibutyrophobia is the fear of peanut butter sticking to the roof of the mouth.",
"In South Africa, termites and ants are often roasted and eaten by the handful, like popcorn.",
"Every time you lick a stamp, you consume 1/10 of a calorie.",
"Pearls melt in vinegar.",
"The 57 on the Heinz ketchup bottle represents the number of pickle types the company once had.",
"Marmite was first introduced into the UK in 1902.",
"The ancient Greeks chewed a gum-like substance called mastic that came from the bark of a tree.",
"Honeybee workers must visit 2 million flowers to make one pound of honey.",
"The fear of vegetables is called Lachanophobia.",
"Almonds are a member of the peach family.",
"If you boil beetroot in water, and then massage the water into your scalp each night, it works as an effective cure for dandruff.",
"In the United States, lettuce is the second most popular fresh vegetable.",
"Grape growing is the largest food industry in the world as there are more than 60 species and 8000 varieties of grapes.",
"The average person eats eight pounds of grapes each year.",
"There are more than 7,000 varieties of apples grown in the world.",
"A cluster of bananas is formerly called a hand. Along that theme, a single banana is called a finger.",
"Onion is Latin for large pearl.",
"Pasta is a type of noodle that is used in cooking.",
"It is a staple food of most Italian cuisines.",
"The first reference to pasta, in a book, was in 1154.",
"It is typically made from durum wheat flour.",
"Most pasta falls under two categories -- it is either dry, or it is fresh.",
"There are over 600 types of pasta, and some have over 1300 names.",
"The three most popular pastas are: penne, spaghetti and macaroni.",
"There are many varieties of pasta, such as: long pasta, short pasta, minute pasta, egg pasta, fresh pasta and al forno pasta.",
"Fresh egg pasta contains egg, which makes it all the more tender when cooking.",
"Pasta can be served in multiple ways. It can be mixed with a sauce or a fresh condiment, it can be stirred into soups or stews, and it can also be baked.",
"Fresh pasta is often served with meat, in dishes such as ravioli.",
"Dried pasta doubles in size when cooked and is often served with thick hearty sauces.",
"The traditional Italian way of cooking pasta is known as al dente.",
"If pasta is cooked properly, it should stick to a wall when it is thrown.",
"In Greek mythology, it is believed that the God Vulcan invented a device that made strings of dough. This was the earliest reference to a pasta maker.",
"Nowadays, pasta makers are found in many homes and restaurants.",
"The Ancient Romans used to fry their pasta.",
"The three most popular pasta dishes are: macaroni cheese, spaghetti bolognaise and lasagne.",
"Uncooked dry pasta can be kept for up to a year.",
"Cooked pasta can be frozen and re-eaten within three months.",
"It was traditionally eaten by hand.",
"One cup of cooked pasta is the size of your fist.",
"Italians eat over sixty pounds of pasta, per person, per year.",
"Italy produces 1,432,990 tons of pasta a year.",
"It exports 1.7 million tons a year.",
"The average price for pasta in the UK is 89 pence, making it an affordable meal for all.",
"Pasta has many health benefits, as it is low in calorific value and contains various nutrients and minerals.",
"Pasta can be given to dogs and cats. Its believed in helps them in their growth development and to help their coats glossy and healthy.",
"The National Pasta Association is a worldwide group which enjoys eating and discussing pasta, and its history.",
"October is National Pasta Month."]
console.log((foodFacts));
